### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by santhosh2808**

### CODE REVIEW

**Comment by santhosh2808** [comment]
Created a new issue [Username  #2](https://github.com/fssa-batch3/santhosh.devendran__web_project/issues/2) in GitHub

**Comment by santhosh2808** [comment]
Created a new issue [mobile number  #3](https://github.com/fssa-batch3/santhosh.devendran__web_project/issues/3) in GitHub

**Comment by santhosh2808** [comment]
Created a new issue [password input #4](https://github.com/fssa-batch3/santhosh.devendran__web_project/issues/4) in GitHub

**Comment by santhosh2808** [comment]
Created a new issue [password input  #5](https://github.com/fssa-batch3/santhosh.devendran__web_project/issues/5) in GitHub

**Comment by santhosh2808** [comment]
Created a new issue [new post content input  #6](https://github.com/fssa-batch3/santhosh.devendran__web_project/issues/6) in GitHub

**Comment by santhosh2808** [comment]
Created a new issue [New post #7](https://github.com/fssa-batch3/santhosh.devendran__web_project/issues/7) in GitHub

**Comment by santhosh2808** [comment]
Created a new issue [user posts #8](https://github.com/fssa-batch3/santhosh.devendran__web_project/issues/8) in GitHub

**Comment by BoobalanRP** [comment]
Created a new issue [The password pattern is not known #9](https://github.com/fssa-batch3/santhosh.devendran__web_project/issues/9) in GitHub

**Comment by BoobalanRP** [comment]
Created a new issue [Error editing profile details #10](https://github.com/fssa-batch3/santhosh.devendran__web_project/issues/10) in GitHub

**Comment by BoobalanRP** [comment]
Created a new issue [Deleting the account didn't work #11](https://github.com/fssa-batch3/santhosh.devendran__web_project/issues/11) in GitHub

**Comment by BoobalanRP** [comment]
Created a new issue [Logout problem #12](https://github.com/fssa-batch3/santhosh.devendran__web_project/issues/12) in GitHub

**Comment by BoobalanRP** [comment]
Created a new issue [Creating a post without any content #14](https://github.com/fssa-batch3/santhosh.devendran__web_project/issues/14) in GitHub

**Pull request merged**
